apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor
  namespace: kube-ops
  labels:
    app: harbor
spec:
  capacity:
    storage: 30Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.16.81.189
    path: /data/nfs/harbor

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: harbor
  namespace: kube-ops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  selector:
    matchLabels:
      app: harbor
