apiVersion: v1
kind: Namespace
metadata:
  name: harbor-system

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor
  namespace: harbor-system
  labels:
    app: harbor
spec:
  capacity:
    storage: 60Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.7
    path: /data/nfs/harbor

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: harbor
  namespace: harbor-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
  selector:
    matchLabels:
      app: harbor
